### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by winni2k** [bcgsc/transabyss#10]
From the github page it appears as if any python above 2.7.10 is supported. Does that include python 3?  If so, then I have a bug to report:
```bash
python3 ~/down/transabyss-2.0.0/transabyss
Traceback (most recent call last):
  File "/Users/winni/down/transabyss-2.0.0/transabyss", line 17, in <module>
    from utilities import psl_cid_extractor
  File "/Volumes/mac-3/home/Downloads/transabyss-2.0.0/utilities/psl_cid_extractor.py", line 140
    print cid
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print cid)?
```

**Comment by kmnip** [comment]
That syntax for `print` works for Python 2, but I can definitely add support for Python 3.

**Comment by winni2k** [comment]
Lack of python3 support is not the end of the world. I got transabyss to work inside a MinicConda2 environment with less than two hours of setup.  I'd just say: state the lack of python3 support explicitly in the docks.  FWIW, the [ruby world](https://bundler.io/gemfile.html#gemfiles) specifies that constraint this way: `~> 2.7.10`

**Comment by kmnip** [comment]
I have made a new release ([2.0.1](https://github.com/bcgsc/transabyss/releases/tag/2.0.1)) that provides support for both Python 2 and Python 3. We have also switched the license to GPL3.

Please let us know if there are any more issues. Closing issue now.

Thanks,
Ka Ming

**Comment by winni2k** [comment]
Cheers!
