### ISSUE TITLE
Conda problems, instalation

### ISSUE THREAD

**Issue by OnlyHigh** [bcgsc/transabyss#12]
Hi, I'm trying to install Trans-Abyss through Conda, but apparently it's not longer available, 
There's another way to install it?
```
(Miscpy27) [larteag7@cronos Purpureocillium]$ conda install -c bioconda transabyss
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - transabyss
  - python-igraph

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
Thanks in advance, 
Luis Alfonso.

**Comment by sjackman** [comment]
I've created PR https://github.com/brewsci/homebrew-science/pull/217 to add Trans-ABySS to Brewsci/bio for Homebrew and Linuxbrew.
```sh
brew install brewsci/bio/transabyss
```

@kmnip Would you like to add a `setup.py` file and add Trans-ABySS to PyPI? I did this for Tigmint, and it's pretty straight forward. See…
https://github.com/bcgsc/tigmint/blob/master/setup.py
Once you've done that, it's even easier to Trans-ABySS to Bioconda. See…
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/tigmint/meta.yaml

**Comment by sjackman** [comment]
I've merged PR https://github.com/brewsci/homebrew-bio/pull/470 to add Trans-ABySS to Brewsci/bio.
```sh
brew install brewsci/bio/transabyss
```

**Comment by OnlyHigh** [comment]
Hi Shaun, 
It worked!
Thanks! 
Luis

**Comment by sjackman** [comment]
Glad to hear it, Luis!
