### ISSUE TITLE
Update conda version

### ISSUE THREAD

**Issue by kokyriakidis** [bcgsc/transabyss#14]
@sjackman @kmnip Hello! Could you please update conda version to 2.01?

**Comment by sjackman** [comment]
I don't have time myself. Here's the file(s) that need to be edited.
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/transabyss

**Comment by winni2k** [comment]
I have started a PR to bioconda-recipes: https://github.com/bioconda/bioconda-recipes/pull/13122

**Comment by winni2k** [comment]
The PR has been merged successfully, which means that an updated conda package will be available soon. @kokyriakidis, please try downloading and running the new package when it comes online and let us know if it works.

**Comment by sjackman** [comment]
Excellent. Thank you, Winni!
