### ISSUE TITLE
Correct specification of paired-end reads

### ISSUE THREAD

**Issue by winni2k** [bcgsc/transabyss#15]
This is just a question to make sure I understood the `README.md` correctly. If I want to assemble regular paired-end reads stored in separate files (not strand-specific), then the correct way to do that is with this command?

```
transabyss --se forward.fq.gz reverse.fq.gz --pe forward.fq.gz reverse.fq.gz
```

**Comment by sjackman** [comment]
@kmnip @readmanchiu  I looked in `sample_dataset/assemble.sh` for an example. It uses `--se`. Should that be `--pe`?

https://github.com/bcgsc/transabyss/blob/05e0b2ca5fe241891be308279d43aabe3311fd57/sample_dataset/assemble.sh#L23-L26

**Comment by sjackman** [comment]
@winni2k I believe that 
```sh
transabyss --se forward.fq.gz reverse.fq.gz --pe forward.fq.gz reverse.fq.gz
```
and
```sh
transabyss --pe forward.fq.gz reverse.fq.gz
```
are equivalent. I'd be inclined to use the latter. Ka Ming or Readman can confirm.

https://github.com/bcgsc/transabyss/blob/master/TUTORIAL.md#13-input-reads

**Comment by kmnip** [comment]
@winni2k , you only need to use the `--pe` option for pair-end RNA-seq data, eg.

`transabyss --pe forward.fq.gz reverse.fq.gz`

If you have more than one set of paired-end read files (eg. libraries "A" and "B"), then:

`transabyss --pe libraryA_forward.fq.gz libraryA_reverse.fq.gz libraryB_forward.fq.gz libraryB_reverse.fq.gz`

**Comment by kmnip** [comment]
@sjackman 
That script was meant to be a _very_ quick test to see if ABySS could be run from the PATH, but I can probably change it in the next release.

**Comment by winni2k** [comment]
Cheers!
