### ISSUE TITLE
awk files not found

### ISSUE THREAD

**Issue by 54mu** [bcgsc/transabyss#16]
Hi,
I installed transabyss via bioconda, within the Oyster River Protocol, after working a first time, now i get a missing files error:

Found Trans-ABySS directory at: /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/lib/python3.6/site-packages
Found Trans-ABySS `bin` directory at: /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/lib/python3.6/site-packages/bin
No such file: skip_psl_self.awk
No such file: skip_psl_self_ss.awk
Found `abyss-pe' at /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/bin/abyss-pe
Found `MergeContigs' at /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/bin/MergeContigs
Found `abyss-filtergraph' at /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/bin/abyss-filtergraph
Found `abyss-junction' at /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/bin/abyss-junction
Found `blat' at /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/bin/blat
Found `abyss-map' at /mnt/DATA/Software/Oyster_River_Protocol/software/anaconda/install/envs/orp/bin/abyss-map
ERROR: Your environment is not sufficient to run Trans-ABySS. Please check the missing executables, scripts, or directories.

do you have any insight? 
Thanks

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Glad to hear that you found a fix.
