### ISSUE TITLE
Can't get the sample dataset to work

### ISSUE THREAD

**Issue by alissawilliams** [bcgsc/transabyss#19]
Hello-

I'm trying to get transabyss set up on a server. I converted assemble.sh into a slurm script:
```
#!/bin/bash
cd /x/y/transabyss-master/sample_dataset/

ml python/2.7.14
export PYTHONPATH=$PYTHONPATH:/projects/amwill@colostate.edu/python2.7/lib/python2.7/site-packages/

set -euo pipefail

cd $(dirname $0)

kmer1=25
kmer2=32
name1=test.k${kmer1}
name2=test.k${kmer2}
reads1=./reads/rnaseq_1.fq.gz
reads2=./reads/rnaseq_2.fq.gz
assemblydir1=./${name1}
assemblydir2=./${name2}
finalassembly1=${assemblydir1}/${name1}-final.fa
finalassembly2=${assemblydir2}/${name2}-final.fa
mergedassembly=./merged.fa

# set up the environment
TRANSABYSS_PATH=$(readlink -f ..)
export PATH=${TRANSABYSS_PATH}:${TRANSABYSS_PATH}/bin/:${PATH}

# assemble the test dataset
transabyss -k ${kmer1} --se ${reads1} ${reads2} --outdir ${assemblydir1} --name 
${name1} --threads 2 --island 0 -c 1

transabyss -k ${kmer2} --se ${reads1} ${reads2} --outdir ${assemblydir2} --name 
${name2} --threads 2 --island 0 -c 1

transabyss-merge --mink ${kmer1} --maxk ${kmer2} --prefixes k${kmer1}. k${kmer2}
. --out ${mergedassembly} ${finalassembly1} ${finalassembly2}

#EOF

```
The software seems to find all of the needed dependencies fine. However, now that I have that part figured out, I keep getting this error:

`transabyss: error: No such file or directory ./reads/rnaseq_1.fq.gz`

I have tried running the bash script from both transabyss-master and transabyss-master/sample_dataset with no luck. Do you know what my issue is?

Thanks,
Alissa Williams

**Comment by ckeeling** [comment]
Hi Alissa,

Sometimes I have found that some programs do not like relative locations for files, because they use the file name as a prefix for the files generated.  Try making a soft link to the read files and see if that helps.

e.g. 
```
ln -s ./reads/rnaseq_1.fq.gz reads1.fq.gz
ln -s ./reads/rnaseq_2.fq.gz reads2.fq.gz
```
then
```
...
reads1=reads1.fq.gz
reads2=reads2.fq.gz
...
```

**Comment by alissawilliams** [comment]
Thank you for the quick reply! I made the symbolic links and reran the script, but I still get the same error. :/

**Comment by ckeeling** [comment]
OK, are your reads in /x/y/transabyss-master/sample_dataset/reads, or a subdirectory ./reads of the directory from which you submit your SLURM job (dirname $0)?

**Comment by alissawilliams** [comment]
In the former. Both rnaseq_1.fq.gz and rnaseq_2.fq.gz are located in /x/y/transabyss-master/sample_dataset/reads. I have my slurm script version of assemble.sh in the same folder as assemble.sh (/x/y/transabyss-master/sample_dataset/).

**Comment by ckeeling** [comment]
I think that with SLURM, your $0 is not giving you what you think it will.  On my system, it gives:

In SLURM script
```
cd $(dirname $0)
pwd
```

In output file...
```
/var/spool/slurmd/job25395894
```

Try removing/commenting out both instances of the cd in your SLURM script, since you are already starting where you want to be, and see if that works.

**Comment by kmnip** [comment]
When your job script is submitted with the `sbatch` command, the script is (usually) copied to the compute node and executed from there.

I suggest either replacing your `cd $(dirname $0)` command with an absolute path or use the `-D` option in the `sbatch` command. For example:
````
sbatch -D /path/to/script/dir job_script.sh
````

**Comment by alissawilliams** [comment]
Hi, thank you both! I tried a bunch of different things, but what ended up working (or what seems to have worked) is getting rid of my cd command, and replacing the one already in the script with an absolute path, and then running the slurm script from the sample_dataset directory. 

However, now I'm getting another error:
`transabyss: error: argument --name: expected one argument`

Any ideas as to what this issue is?

Thanks again!
Alissa

**Comment by ckeeling** [comment]
Be sure that your commands starting with transabyss that are shown above as two lines are actually only one line each.  Depending on which text editor you used to convert the script to a SLURM script, you may have inadvertently added a carriage return after the --name.

**Comment by alissawilliams** [comment]
Hi Chris-

You were right; I introduced returns within a command on accident. Thanks! 

I am now getting an error that needed executables can't be found. Do you know where the following are located in the abyss folder? I can't seem to find them.
MergeContigs
abyss-filtergraph
abyss-junction
abyss-map

Thanks,
Alissa

**Comment by ckeeling** [comment]
Have you installed ABySS as well as trans-ABySS as per the readme?  If you are using linuxbrew (suggested), you can install abyss and trans-abyss with:
```
brew install abyss
```

**Comment by alissawilliams** [comment]
I have abyss downloaded, as well as trans-abyss. I thought I had everything installed, but apparently I don't, so I downloaded linuxbrew as well. However, upon trying to install linuxbrew according to the provided instructions, I got stuck because I don't have root privileges on the server I'm working on. sudo is blocked for non-root users, so I'm not able to install linuxbrew in the standard way. I know the documentation says that it can install without sudo, but I'm not sure how to make that happen.

**Comment by alissawilliams** [comment]
Oh! Looks like I can get to a non-sudo option. I'll keep working with that.

**Comment by ckeeling** [comment]
You definitely don't need root access to install and use linuxbrew.  That is one of its advantages; once installed, you can install almost anything within the brew universe in your home space, and it usually does an excellent job of installing dependencies etc.  Good luck!

**Comment by alissawilliams** [comment]
Thanks for all your help! It is much appreciated!
