### ISSUE TITLE
Trans-ABySS not compatible with icu=67.1 on bioconda, downgrade to 58.* to use

### ISSUE THREAD

**Issue by selveyad** [bcgsc/transabyss#22]
Howdy Trans-ABySS,

I downloaded the latest Trans-ABySS upload to bioconda (noarch/transabyss-2.0.1-py_6.tar.bz2) on Ubuntu 20.04 and when downloading the ICU dependency, it downloads v67.1:
<pre>
Collecting package metadata (repodata.json): done
Solving environment: done

Package Plan

  environment location: /home/alexanderselvey/miniconda3/envs/transabyss

  added / updated specs:
    - transabyss

The following NEW packages will be INSTALLED:

  abyss              bioconda/linux-64::abyss-2.0.2-h51208dd_5
  blat               bioconda/linux-64::blat-36-0
  bwa                bioconda/linux-64::bwa-0.7.17-hed695b0_7
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  cairo              conda-forge/linux-64::cairo-1.16.0-h3fc0475_1004
  curl               conda-forge/linux-64::curl-7.69.1-h33f0ec9_0
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h1056068_1002
  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.64.3-h6f030ca_0
  gmp                conda-forge/linux-64::gmp-6.2.0-he1b5a44_2
  <b>icu                conda-forge/linux-64::icu-67.1-he1b5a44_0</b>
  igraph             conda-forge/linux-64::igraph-0.7.1-4
  krb5               conda-forge/linux-64::krb5-1.17.1-h2fd8d38_0
  libcurl            conda-forge/linux-64::libcurl-7.69.1-hf7181ac_0
  libdeflate         bioconda/linux-64::libdeflate-1.0-h14c3975_1
  libedit            conda-forge/linux-64::libedit-3.1.20191231-h46ee950_0
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_6
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_1
  libssh2            conda-forge/linux-64::libssh2-1.9.0-hab1572f_2
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.10-h72b56ed_1
  make               conda-forge/linux-64::make-4.3-h516909a_0
  mpi                conda-forge/linux-64::mpi-1.0-openmpi
  openmpi            conda-forge/linux-64::openmpi-4.0.3-hdf1f1ad_1
  pandoc             conda-forge/linux-64::pandoc-2.9.2.1-0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  perl               conda-forge/linux-64::perl-5.26.2-h516909a_1006
  pixman             conda-forge/linux-64::pixman-0.38.0-h516909a_1003
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pycairo            conda-forge/linux-64::pycairo-1.19.1-py38h323dad1_3
  python-igraph      conda-forge/linux-64::python-igraph-0.7.1.post7-py38h516909a_0
  samtools           bioconda/linux-64::samtools-1.9-h8571acd_11
  transabyss         bioconda/noarch::transabyss-2.0.1-py_6
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h516909a_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h84519dc_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.9-h516909a_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
</pre>

When I run `$transabyss` I get this error:
```
Traceback (most recent call last):
  File "/home/alexanderselvey/miniconda3/envs/transabyss/bin/transabyss", line 18, in <module>
    from transabyss.adj_utils import has_edges
  File "/home/alexanderselvey/miniconda3/envs/transabyss/lib/python3.8/site-packages/transabyss/adj_utils.py", line 6, in <module>
    import igraph
  File "/home/alexanderselvey/miniconda3/envs/transabyss/lib/python3.8/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```
I remedied that by downloading ICU v58.2 with `conda install icu=58.*`

It now works. I'm not sure if you can set the particular ICU dependency it downloads with, but if so, it should be set to ICU v58.2 to prevent others from running into this issue. 

Thanks!

**Comment by kmnip** [comment]
Thanks reporting this!
It looks like that was an issue with the igraph package. I think the issue would be resolved if the `conda` recipe were updated to newer version of igraph (e.g. v0.8.0).

**Comment by selveyad** [comment]
Always! Thanks for the support! I'll let you know if I run into any other little snags, too!
