### ISSUE TITLE
Assembly stopped with error status code 2

### ISSUE THREAD

**Issue by mhfk** [bcgsc/transabyss#23]
Hi folks, 

I attempted to assemble fungal transcriptome using PE and SE reads of which I performed reverse-complement using BBMap reformat.sh. However, I ran into several issues: 
1) The assembler was unable to detect my read orientation which I identified as inwards, stranded and forward (ISF) using Salmon. The assembler declared the library as FF after detecting 112 reads while declared most of the reads as different (I don't know the definition of Different here)

2) The assemble stopped with status code 2

I attached the screenshot for your reference. Is there any solution that I can try? Thank you in advance! 
![ERR](https://user-images.githubusercontent.com/74343404/99835370-781ea200-2b9f-11eb-9302-de65aa641320.png)

**Comment by kmnip** [comment]
Hello @mhfk ,

The assembler crashed because the `abyss-map` aligner expects the mates to be in opposite orientations, i.e.
`----> <----`
So, you should use the original reads as input to Trans-ABySS.

`Different` in the log refers to the number of read pairs that are aligned to different unitigs.
The read orientations (i.e. `FF`, `RF`, and `FR`) are tallied based on the mates aligned to single unitigs. I am actually quite surprised that there are only 112 reads for this.

Ka Ming

**Comment by mhfk** [comment]
Hi @kmnip ,
Apologies for the late follow-up. I have tried to run the alignment using the original reads and the same issue persisted. My workstation froze so I couldn't get the screenshot but the same error message prompted. I wonder if the assembler identified my reads as unstranded and couldn't proceed with assembly.

**Comment by kmnip** [comment]
Can you verify that the read names have the suffixes `/1` and `/2` within your read files?

**Comment by mhfk** [comment]
I think the file names might be the issue. The names of the files were :
Paired-end
> 91_1.paired.fq.gz & 91_2.paired.fq.gz \
> 92_1.paired.fq.gz & 92_2.paired.fq.gz \
> 93_1.paired.fq.gz & 93_2.paired.fq.gz \
> 94_un-conc-mate.1.paired.fq.gz & 94_un-conc-mate.2.paired.fq.gz \
> 95_un-conc-mate.1.paired.fq.gz & 95_un-conc-mate.2.paired.fq.gz \
> 96_un-conc-mate.1.paired.fq.gz & 96_un-conc-mate.2.paired.fq.gz \

Single-end
> 91_1.unpaired.fq.gz & 91_2.unpaired.fq.gz & 92_1.unpaired.fq.gz & 92_2.unpaired.fq.gz & 93_1.unpaired.fq.gz & 93_2.unpaired.fq.gz \
> 94_un-conc-mate.1.unpaired.fq.gz & 94_un-conc-mate.2.unpaired.fq.gz \
> 95_un-conc-mate.1.unpaired.fq.gz & 95_un-conc-mate.2.unpaired.fq.gz & un-singleton.trimmed.fq.gz \
> 96_un-conc-mate.1.unpaired.fq.gz & 96_un-conc-mate.1.unpaired.fq.gz & un-singleton.trimmed.fq.gz

I am changing the file names to names with strand information at the back (*_1.fq.gz or *_2.fq.gz) instead of having them in the middle as seen above. Will let you know if this works!

**Comment by mhfk** [comment]
The error persisted with similar error prompt. Perhaps there is something wrong with my command. I have both PE and SE reads to be assembled. SE reads belong to SE library and residual data from Trimmomatic. Here are the commands :

`transabyss --SS --threads 16 --pe \
> ./axenic/SRR8432491/91.paired_1.fq.gz ./axenic/SRR8432491/91.paired_2.fq.gz \
> ./axenic/SRR8432492/92.paired_1.fq.gz ./axenic/SRR8432492/92.paired_2.fq.gz \
> ./axenic/SRR8432493/93.paired_1.fq.gz ./axenic/SRR8432493/93.paired_2.fq.gz \
> ./inplanta/SRR8432494/94_un-conc-mate.paired_1.fq.gz ./inplanta/SRR8432494/94_un-conc-mate.paired_2.fq.gz \
> ./inplanta/SRR8432495/95_un-conc-mate.paired_1.fq.gz ./inplanta/SRR8432495/95_un-conc-mate.paired_2.fq.gz \
> ./inplanta/SRR8432496/96_un-conc-mate.paired_1.fq.gz ./inplanta/SRR8432496/96_un-conc-mate.paired_2.fq.gz \
> --se \
> ./axenic/SRR8432491/91.unpaired_1.fq.gz ./axenic/SRR8432491/91.unpaired_2.fq.gz ./axenic/SRR8432492/92.unpaired_1.fq.gz ./axenic/SRR8432492/92.unpaired_2.fq.gz ./axenic/SRR8432493/93.unpaired_1.fq.gz ./axenic/SRR8432493/93.unpaired_2.fq.gz \
> ./inplanta/SRR8432494/94_un-conc-mate.unpaired_1.fq.gz ./inplanta/SRR8432494/94_un-conc-mate.unpaired_2.fq.gz \
> ./inplanta/SRR8432495/95_un-conc-mate.unpaired_1.fq.gz ./inplanta/SRR8432495/95_un-conc-mate.unpaired_2.fq.gz ./inplanta/SRR8432495/un-singleton.trimmed.fq.gz \
> ./inplanta/SRR8432496/96_un-conc-mate.unpaired_1.fq.gz ./inplanta/SRR8432496/96_un-conc-mate.unpaired_2.fq.gz ./inplanta/SRR8432496/un-singleton.trimmed.fq.gz `
