### ISSUE TITLE
ERROR: CMD ended with status code 2

### ISSUE THREAD

**Issue by Liyong-Zhang** [bcgsc/transabyss#27]
Hello there,

I am using Trans-ABySS to assemble a transcriptome for my pair-end RNAseq data (3 replicates x 50 genotypes).   I installed Trans-ABySS (v2.0.1) through conda on a Linux server.  The commands are following 
` file_list=($(find /liyong_temp/trimmed/ -type f -name "*P.fq.gz" | sort)) ` 
`out=/transcriptome_assembly/de_novo/transabyss`
`transabyss \
--pe ${file_list[@]} \
--threads 64 \
--length 200 \
--outdir $out`

The log file is:
**/liyong_temp/trimmed/Cs123_trimmed_1P.fq.gz': discarded 5 reads containing non-ACGT characters
   /liyong_temp/trimmed/Cs123_trimmed_2P.fq.gz': discarded 62 reads containing non-ACGT characters
   ........................
   /liyong_temp/trimmed/Cs133_trimmed_1P.fq.gz': discarded 2 reads containing non-ACGT characters
   /liyong_temp/trimmed/Cs133_trimmed_2P.fq.gz': discarded 16 reads containing non-ACGT characters**

**The minimum coverage of single-end contigs is 2.
The minimum coverage of merged contigs is 2.
The minimum coverage of single-end contigs is 0.652174.
The minimum coverage of merged contigs is 2.
Consider increasing the coverage threshold parameter, c, to 2.
The minimum coverage of single-end contigs is 2.
The minimum coverage of merged contigs is 2.
warning: the seed-length should be at least twice k: k=32, s=32
Building the suffix array...
Building the Burrows-Wheeler transform...
Building the character occurrence table...
sort: write failed: /tmp/sortUz7aTQ: No space left on device
error: `transabyss-3.hist': No such file or directory
make: *** [/home/AGR.GC.CA/zhangliy/transabyss_conda/env/bin/abyss-pe.Makefile:559: transabyss-3.dist] Error 1
make: *** Deleting file 'transabyss-3.dist'**

Any suggestion how I could get this to work? 
Many thanks.

**Comment by kmnip** [comment]
Hi,

This part of your log indicates an error:
> sort: write failed: /tmp/sortUz7aTQ: No space left on device

This means your temp directory is full and there wasn't enough space for the `sort` comment.
You can set `TMPDIR` to a local directory. For example:

```
mkdir /transcriptome_assembly/de_novo/transabyss/tmpdir
export TMPDIR=/transcriptome_assembly/de_novo/transabyss/tmpdir
transabyss ...
```

Hope that helps!

**Comment by Liyong-Zhang** [comment]
After I set the tmpdir, it looks all good now.       Thanks!
