### ISSUE TITLE
TranAbyss-Analyze Paired-end Accession Error

### ISSUE THREAD

**Issue by gs1070** [bcgsc/transabyss#4]
Although the paired reads were checked with two different scripts for unpaired reads before running TransAbyss-Analyze, an error saying "the paired-end accessions do not match" is output before aborting. The message essentially says `Paired-end accessions FCC6B7TACXX:7:1101:10524:57301# and FCC6B7TACXX:7:1101:9245:1994# do not match`.

Command:
```
transabyss-analyze -a TrAb_Merged_1_1.fa -1 RG11_NR_P3_R1.fq.gz -2 RG11_NR_P3_R2.fq.gz --SS --ref Gh1 --cfg /work/satishg/transcriptome.cfg --annodir /work/satishg/Gh1.gtf --analyze fusion -o /work/satishg/TrAn_RG11_Gh1 -t 20
```

Error Message:
```
/work/satishg/TrAn_RG11_Gh1/reads_to_genome/cluster/transabyss.local.sh: line 3: ulimit: core file size: cannot modify limit: Operation not permitted
GSNAP version 2014-12-29 called with args: gsnap --gunzip -d Gh1 -D /work/satishg -t 18 --format sam -N 1 -m 10 /work/satishg/RG11_NR_P3_R1.fq.gz /work/satishg/RG11_NR_P3_R2.fq.gz
Checking compiler assumptions for popcnt: 6B8B4567 __builtin_clz=1 __builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17 
Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
Checking compiler assumptions for SSE4.1: -103 -58 max=-58 => compiler sign extends
Finished checking compiler assumptions
Novel splicing (-N) turned on => assume reads are RNA-Seq
Paired-end accessions FCC6B7TACXX:7:1101:10524:57301# and FCC6B7TACXX:7:1101:9245:1994# do not match
real    0m0.623s
user    0m0.009s
sys     0m0.056s
ERROR: Execution of script ended with a non-zero exit-status.
```

I tried running it with three different read pairs but all terminate with the same error. 
Please suggest a fix for the same.

**Comment by kmnip** [comment]
This error actually came from GSNAP. I suggest running the gsnap command separately, ie,

```
gsnap --gunzip -d Gh1 -D /work/satishg -t 18 --format sam -N 1 -m 10 /work/satishg/RG11_NR_P3_R1.fq.gz /work/satishg/RG11_NR_P3_R2.fq.gz
```

If you can reproduce the error, then please report to the author of GMAP/GSNAP:
http://research-pub.gene.com/gmap/

**Comment by gs1070** [comment]
How do I get to know the various steps run on TransAbyss-Analyze? Is there
a command for dry-run like in Abyss with "-n" option?

**Comment by kmnip** [comment]
Sorry, no. There is no such option.

**Comment by gs1070** [comment]
OK. I am trying to run the command you suggested. The job is in queue and
shall get back with you when I have the output.

**Comment by gs1070** [comment]
Still doesn't run:

GSNAP version 2014-12-29 called with args: gsnap --gunzip -d Gh1 -D
/work/satishg -t 18 --format sam -N 1 -m 10
/work/satishg/RG11_NR_P3_R1.fq.gz /work/satishg/RG11_NR_P3_R2.fq.gz
Checking compiler assumptions for popcnt: 6B8B4567 __builtin_clz=1
__builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17
Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
Checking compiler assumptions for SSE4.1: -103 -58 max=-58 => compiler sign
extends
Finished checking compiler assumptions
Novel splicing (-N) turned on => assume reads are RNA-Seq
Paired-end accessions FCC6B7TACXX:7:1101:10524:57301# and
FCC6B7TACXX:7:1101:9245:1994# do not match

Please advise......

**Comment by kmnip** [comment]
Well, you have confirmed the problem. :)
If you are 100% sure that your read files are paired properly, then please
report this error to the developer of GMAP/GSNAP.
