### ISSUE TITLE
make fail for abyss1.5.2/1.5.1

### ISSUE THREAD

**Issue by cd-ccmb** [bcgsc/transabyss#7]
I need to work with transabyss for RNAseq analysis, I am unable to install abyss1.5.2 as the make fails for one or other module (Layout, Overlap,Konnector,etc) depending on what boost I use. I have tried the latest boost (1.64.0) as well several other (1.55.0,1.52.0,1.40.0) to configure and make abyss but I have failed. I even tried installing transabyss 1.5.3 with abyss 1.5.1 but failed to do so too. Could you please help me with this. I am working on Fedora 4.8
1. how to install abyss1,5,2 successfully for using transabyss? Which boost library to use?
2.Can I use the latest abyss2.0 for transabyss 1.5.5?

Thanks

**Comment by sjackman** [comment]
@benvvalk Any thoughts?

**Comment by benvvalk** [comment]
@kmnip did some brief testing of TransABySS with ABySS 2.0 and unfortunately he said he ran into some issues beyond just adding `graph=dot` to the abyss-pe command.  He said one of the dependent ABySS tools was crashing (`abyss-junction`, I think), and there were perhaps some other issues as well.

I agree it would be good to address these things and make a new Trans-ABySS release that works with the latest ABySS.  I've got a lot to do at the moment w.r.t. to ABySS itself, though.  It would be nice if we could get someone else on the team to be the official Trans-ABySS steward.

**Comment by cd-ccmb** [comment]
Yes I tried running transabyss with abyss 2.0 as well and the abyss-junction module fails to run. Can we expect a newer release of transabyss with abyss2.0 soon? Additionally the boost library issue needs to be addressed well for abyss 1.5.2. 

Thanks

**Comment by kmnip** [comment]
Yes, that was part of the reason why a new version of Trans-ABySS hasn't
been released. That being said, we still use ABySS 1.5.3 routinely with
Trans-ABySS for our projects. Not sure why ABySS didn't compile on your
system?

**Comment by cd-ccmb** [comment]
Ok the installation guideline for transabyss 1.5.5 says to use abyss 1.5.2,  will try compiling abyss1.5.3 and using it. Thanks

**Comment by kmnip** [comment]
You may use ABySS 2.0 with Trans-ABySS now. Please see our latest release. 
I am closing this issue. Let us know if you encounter any more problems with running Trans-ABySS.

Thanks,
Ka Ming

**Comment by benvvalk** [comment]
You rock, @kmnip!
