### ISSUE TITLE
installation with conda

### ISSUE THREAD

**Issue by webbchen** [bcgsc/transabyss#8]
good morning

I installed Trans ABySS with conda, but for some reason the awk scripts are not being found. Where do I need to put them so they're found?
When I enter
$ transabyss

I get the following message:
"
Trans-ABySS 1.5.4
CMD: /data/software/Python/anaconda2/bin/transabyss
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Found Trans-ABySS directory at: /data/software/Python/anaconda2/lib/python2.7/site-packages
Found Trans-ABySS `bin` directory at: /data/software/Python/anaconda2/lib/python2.7/site-packages/bin
No such file: skip_psl_self.awk
No such file: skip_psl_self_ss.awk
Found `blat' at /data/software/Python/anaconda2/bin/blat
Found `MergeContigs' at /data/software/abyss-2.0.2/MergePaths/MergeContigs
Found `abyss-filtergraph' at /data/software/abyss-2.0.2/FilterGraph/abyss-filtergraph
Found `abyss-map' at /data/software/abyss-2.0.2/Map/abyss-map
Found `abyss-pe' at /data/software/abyss-2.0.2/bin/abyss-pe
Found `abyss-junction' at /data/software/abyss-2.0.2/Scaffold/abyss-junction
ERROR: Your environment is not sufficient to run Trans-ABySS. Please check the missing executables, scripts, or directories.
"
Where would I expect these files to be?

Kind regards,

Anne

**Comment by webbchen** [comment]
update: The error goes away if the awk scripts are in the current working directory. Is that deliberate? If yes, it may be worth pointing that out in the documentation.
Kind regards,

Anne

**Comment by sjackman** [comment]
Hi, Anne. Thanks for the bug report and workaround. Are you interested and inclined to submit a PR to Bioconda to fix the build script?
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/transabyss

**Comment by webbchen** [comment]
Hello,
I wonder if it's to do with this change in transabyss.patch, lines 53 to 56:

-SKIP_PSL_SELF = os.path.join(BINDIR, 'skip_psl_self.awk')
-SKIP_PSL_SELF_SS = os.path.join(BINDIR, 'skip_psl_self_ss.awk')
+SKIP_PSL_SELF = 'skip_psl_self.awk'
+SKIP_PSL_SELF_SS = 'skip_psl_self_ss.awk'
I'm reluctant to make a full pull request because I have no idea if that's what caused the problem.

**Comment by lalalagartija** [comment]
I had the same issue.

I could not found the file  transabyss.patch 

What worked for me (the job is not finished yet, we'll  see) is to manually set the BINDIR in 
conda/envs/transabyss/lib/python3.6/site-packages/transabyss/package_info.py to 
`BINDIR= ".../conda/envs/transabyss/bin"`
weirdly, it was not enough, I also had to do a symlink
`ln -s ...conda/envs/transabyss/bin/skip_psl_self* .`
