### ISSUE TITLE
ABySS 2.0.2

### ISSUE THREAD

**Issue by mspiffy** [bcgsc/transabyss#9]
We are getting later run-errors with ABYSS 2.0.2 in conjunction with Trans-ABySS, which is basically a known issue. https://github.com/bcgsc/abyss/issues/159

> reads containing non-ACGT characters make: *** No rule to make target 'transabyss-1.adj'. Stop. 

If there is anything to instrument this on the pipelines used for debugging, would be happy to help.

**Comment by kmnip** [comment]
I will be releasing a version 2 of Trans-ABySS that is compatible with ABySS v2.0.x

**Comment by kmnip** [comment]
Trans-ABySS 2.0.0 is released. I am closing this issue now. Please let us know if you see anymore issues.

Thanks,
Ka Ming
